name: my_env
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - sqlalchemy=2.0.48
  - ipykernel
  - jupytext
  - psycopg2=2.9.11
  - pymysql
  - pip:
      - snowflake-sqlalchemy
      - snowflake-snowpark-python
      - sqlalchemy-redshift
      - redshift-connector
      - psycopg2-binary==2.9.11